name: Branch Protection Settings

# This file documents the branch protection settings that should be applied
# on GitHub. These settings need to be manually configured in the GitHub repository settings.

# Branch Protection for 'main' branch
main:
  # Require pull request reviews before merging
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false

  # Require status checks to pass before merging
  required_status_checks:
    strict: true
    contexts:
      - test-and-lint

  # Restrict who can push to the branch
  restrictions:
    users: []
    teams: []
    apps: []

  # Do not allow bypassing the above settings
  enforce_admins: true

  # Do not allow deletion of the branch
  allow_deletions: false

  # Do not allow force pushes to the branch
  allow_force_pushes: false
# How to apply these settings:
# 1. Go to your GitHub repository
# 2. Click on "Settings"
# 3. Click on "Branches" in the left sidebar
# 4. Under "Branch protection rules", click "Add rule"
# 5. Enter "main" as the branch name pattern
# 6. Configure the settings as described above
# 7. Click "Create" or "Save changes"
