name: Branch Protection

on:
  push:
    branches:
      - main

jobs:
  check-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check if push is from PR
        run: |
          # If the push is from a PR merge, the GitHub event will have a pull_request object
          if [ "${{ github.event_name }}" == "push" ] && [ -z "${{ github.event.pull_request }}" ]; then
            # Check if the actor is a GitHub Action (for automated workflows)
            if [[ "${{ github.actor }}" != "github-actions[bot]" && "${{ github.actor }}" != "dependabot[bot]" ]]; then
              echo "ERROR: Direct pushes to the main branch are not allowed."
              echo "Please create a feature branch and submit a pull request instead."
              exit 1
            fi
          fi 